apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: thush1990/repo1:api2
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: postgres://user:password@postgres:5432/db
            - name: NODE_ENV
              value: development